language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: NN9/Byp7TjOYedRNx3li7d/hXsKKcP0A7MpVCK5U6B/Y42X8DLJ/yWKv7ws2HAflVCm9Dp2M8w5bpOWBhHx83NSBzSMtw4yAI8kWS1CXonFYk3MqVPIFJ4HzIzuTCa//Jf8R5uEMizGqBqGhe0rtZJ4q6dHU5DTRS3cVLxes6FJNSuLp3gF6eiKA5YbmruHQoQ0lRalf0TGrwHsaqctihztVrSCLKRmbJvx72LL0k7HnwgH5KcCyDKD0+NZc/GJXVpWFN61YzOKfSgAHpjs4ws/OWnBURG01S6PAFeMSlBPO84JCHWCLCxlEMTsl6o04sT1HsKdFJjHiLwMaYy9r1RHNZCA0jmW0koGiAAPAMNydPnNFBQYmdOrdl+kPhgkdUus4mA/jtT76j9xZ138IrBvTb8MXwqrTGMO67WxWSiAi7OHf9/Qyx+8qMHtIyKSixyqpn3V2moKBaweOryEVoSm8vqwIcPKGwxiMV+oQuoM3uNfww69JTeKmeD2aKYjYETuF95D1gmaZiPnuKBu9u5FwbDkkQ61BiRMpbNwjhcChIiw+EU73eBR1h/DwHq0W3aUSXcgMVQ+sI5o3usAJmglkA/FBeWQML8mRrZeszPXpfN2qRcIcrEraLUJUQVnEUErOBIu4FpAzwPOBDjccJTy45NJPmbaDMfc8ARrRGm4=
  app: simple-web-app-learn-pipeline